### ISSUE TITLE
Journel

### ISSUE THREAD

**Issue by sim2kid** [trashyvoid-art/Mystery_Manor#3]
A journal that shows the history of what has been found

**Comment by trashyvoid-art** [comment]
notes automatically update when you investigate an item relevant to the case, and when you ask characters about alibis / clues; players should also be able to input their own notes
one thing specifically i think is that they should be numbered as entries for organization

**Comment by sim2kid** [comment]
> notes automatically update when you investigate an item relevant to the case, and when you ask characters about alibis / clues; players should also be able to input their own notes one thing specifically i think is that they should be numbered as entries for organization

Would you like those entries numbered by the order they're added or predetermined by the script (which would then put the weight on the writers)

**Comment by trashyvoid-art** [comment]
> > notes automatically update when you investigate an item relevant to the case, and when you ask characters about alibis / clues; players should also be able to input their own notes one thing specifically i think is that they should be numbered as entries for organization
> 
> Would you like those entries numbered by the order they're added or predetermined by the script (which would then put the weight on the writers)

by the order they're added please! another thing i thought about as well is notes should always be accessible + this is more a UI note on me but i think we should go for page turning rather than scrolling

**Comment by sim2kid** [comment]
Potential UML
class Entry
+ int EntryID  - set
+ string EntryContent - set
+ bool CustomEntry - set

+ Entry(int id, string content, bool custom entry = false)
+ DeleteEntry() [Only works if CustomEntry]
+ UpdateEntry(string) [Only works if CustomEntry]

class Journel
+ List<Entry> Entries 

+ AddEntry(string content)
